#!/bin/sh

APPNAME=`basename $0`

if [ ! -d .git ]; then
  echo "$APPNAME: this is not a Git repository. Giving up"
  exit 1
fi

if [ ! -d include ]; then
  echo "$APPNAME: include directory not found. Giving up"
  exit 1
fi

SHORT=`git describe`
LONG=`git describe --tags --long`

MAJOR=`echo $SHORT | cut -f1 -d '.'`
MINOR=`echo $SHORT | cut -f2 -d '.'`
PATCH=`echo $LONG | cut -f2 -d '-'`
BUILD=`echo $LONG | cut -f3 -d '-'`

echo $LONG > .version
echo $SHORT > VERSION

echo "// This file is autogenerated by build-aux/version.sh" > include/version.h
echo "// * PLEASE DO NOT EDIT THIS FILE *" >> include/version.h
echo "// Last update: `date`" >> include/version.h
echo "#ifndef _VERSION_H" >> include/version.h
echo "#define _VERSION_H" >> include/version.h
echo "#define MAJOR \"$MAJOR\"" >> include/version.h
echo "#define MINOR \"$MINOR\"" >> include/version.h
echo "#define PATCH \"$PATCH\"" >> include/version.h
echo "#define BUILD \"$BUILD\"" >> include/version.h
echo "#define FULL_VERSION \"$LONG\"" >> include/version.h
echo "#endif" >> include/version.h

# Last echo is for configure script
echo $SHORT | tr -d '\012'
